Repository mash-up-kr/Constellation-Diary-iOS, pull requests merged in 2020-01, with the labels that each got.

#40 Feature/diary ui
  StarStarDiary.xcodeproj/project.pbxproj
  StarStarDiary/Assets.xcassets/Color/Navy3.colorset/Contents.json
  StarStarDiary/Extensions/Date+.swift
  StarStarDiary/Extensions/DateFormatter+.swift
  StarStarDiary/Extensions/UIColor+Resource.swift
  StarStarDiary/Sample.json
  StarStarDiary/ViewControllers/DiaryListViewController.swift
  StarStarDiary/ViewControllers/SideMenuViewController.swift
  StarStarDiary/Views/BaseNavigationView.swift
  StarStarDiary/Views/Diary.swift
  StarStarDiary/Views/DiaryTableHeaderView.swift
  StarStarDiary/Views/DiaryTableViewCell.swift
Labels: bug

#46 feat: 일기 작성 화면 디자인 적용
  StarStarDiary/ViewControllers/WriteViewController.swift
Labels: design, feature

#43 Feature/constellation selection ui
  Podfile.lock
  StarStarDiary.xcodeproj/project.pbxproj
  StarStarDiary/AppDelegate.swift
  StarStarDiary/Common/Reusable.swift
  StarStarDiary/Extensions/UICollectionView+.swift
  StarStarDiary/Models/Constellation.swift
  StarStarDiary/ViewControllers/ConstellationSelectionViewController.swift
  StarStarDiary/Views/Cell/ConstellationCell.swift
Labels: design

#45 Feature/sign up ui
  StarStarDiary.xcodeproj/project.pbxproj
  StarStarDiary/Assets.xcassets/icComplete24White.imageset/Contents.json
  StarStarDiary/Assets.xcassets/icComplete24White.imageset/icComplete24White.png
  StarStarDiary/Assets.xcassets/icComplete24White.imageset/icComplete24White@2x.png
  StarStarDiary/Assets.xcassets/icComplete24White.imageset/icComplete24White@3x.png
  StarStarDiary/Extensions/UIView+.swift
  StarStarDiary/ViewControllers/SignUpViewController.swift
  StarStarDiary/ViewControllers/VarifyEmailViewController.swift
  StarStarDiary/Views/InputFormView.swift
Labels: design, feature
